### ISSUE TITLE
Out of memory warning/error

### ISSUE THREAD

**Issue by MadcapJake** [MadcapJake/citrine-json#1]
I am getting a warning/error from (iiuc) the heap allocator:
```
Out of memory. Failed to allocate 56 bytes.
```
@gabordemooij do you have any idea why I'd be getting that?

The `010-basic.ctr` file runs fine, it just ends with that message.

**Comment by gabordemooij** [comment]
Interesting.

Citrine keeps track of memory to ensure there are no memory leaks. For some reason the code seems to be subtracting too much from heap resulting in an overflow, making Citrine think too much memory has been requested.

If you remove the last line 'json put' you will get another error:

[WARNING] Citrine has detected an internal memory leak of: 56 bytes.

I assume these two messages are related since the original message also mentions the exact same number of bytes.

**Comment by gabordemooij** [comment]
Hmmm

`ctr_object* jsonObject = ctr_json_new(CtrStdWorld, NULL);`

here you pass the World as first param, but here:

```
ctr_object* ctr_json_new(ctr_object* myself, ctr_argument* argumentList) {

...
	return ctr_json_internal_addjobj(myself, json_object_new_object());
}
```


you use myself as the new object?

**Comment by gabordemooij** [comment]
Using 

`return ctr_json_internal_addjobj(jsonObjectInstance, json_object_new_object());`

in ctr_json_new

seems to fix the memory leak

the allocation error remains though, but only if you invoke the non-existing message 'put'.

**Comment by gabordemooij** [comment]
that might be due to the circular reference created in the new-function, to fix that I added:

`jsonObject->link = CtrStdObject;`

to your begin() function.

**Comment by gabordemooij** [comment]
Now it runs smoothly over here.

**Comment by gabordemooij** [comment]
So my changes are:

begin():
add:

` jsonObject->link = CtrStdObject;`

and in ctr_json_new:

`return ctr_json_internal_addjobj(jsonObjectInstance, json_object_new_object());`

(use jsonObjectInstance instead of myself)

**Comment by gabordemooij** [comment]
Hope this works for you as well, please let me know.

**Comment by gabordemooij** [comment]
Love your work by the way. Beautiful code ;)

**Comment by MadcapJake** [comment]
This is fixed now
